<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../SarifRegress.Core/SarifRegress.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SarifRegress.Cli" />
    <InternalsVisibleTo Include="SarifRegress.DeterminismTests" />
  </ItemGroup>
</Project>
